//using Unity.Entities;
//using Unity.Jobs;
//using Unity.Mathematics;
//using Unity.Collections;
//using Unity.Transforms;
//using Unity.Burst;
///// <summary>
///// System that reacts on panic spots, generated by mouse click.
///// </summary>
//public class RunningSystem : JobComponentSystem
//{
//    //[BurstCompile]
//    public struct RunningJob : IJobForEachWithEntity<Translation, AgentComponent, MoveSpeedComponent>
//    {
//        public float deltaTime;
//        public void Execute(Entity entity, int index, ref Translation translation, ref AgentComponent agentComponent, [ReadOnly] ref MoveSpeedComponent moveSpeedComponent)
//        {
//            if (agentComponent.agentStatus == AgentStatus.Running && agentComponent.hasTarget)
//            {
//                // Agent has panic, need to run to the next closest escape spot
//                float3 direction = math.normalize(agentComponent.target - translation.Value);
//                translation.Value += direction * moveSpeedComponent.runningSpeed * deltaTime;
//            }
//        }
//    }

//    /// <summary>
//    /// Runs on main thread, 1 times per frame
//    /// </summary>
//    /// <param name="inputDeps"></param>
//    /// <returns></returns>
//    protected override JobHandle OnUpdate(JobHandle inputDeps)
//    {
//        // Schedule panicJob
//        var runningJob = new RunningJob
//        {
//            deltaTime = UnityEngine.Time.deltaTime
//        }.Schedule(this, inputDeps);

//        return runningJob;
//    }
//}
